version: '3.9'
services:
  db:
    image: postgres:16
    container_name: bookclub-db
    environment:
      POSTGRES_USER: bookuser
      POSTGRES_PASSWORD: bookpass
      POSTGRES_DB: bookclub
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U bookuser -d bookclub']
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  db_data:
